#!/usr/bin/env node
// Generates src/abis/*.ts (`as const` ABI arrays) from contracts/out and src/addresses.ts from
// contracts/deployments/<chainId>.json. Run `forge build` in contracts/ first.
// Usage: npm run gen -w @company/abi   (or: node scripts/gen-abi.mjs)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");
const contracts = resolve(pkg, "../../contracts");
const outDir = join(contracts, "out");
const deploymentsDir = join(contracts, "deployments");
const abisDir = join(pkg, "src", "abis");

// [export name, artifact "<File>.sol/<Contract>"]
const ARTIFACTS = [
  // $COMD is the external Pons token: a plain ERC-20 ABI (MockComd stands in on test chains; no burn()).
  ["ComdToken", "MockComd.sol/MockComd"],
  ["CounselNFT", "CounselNFT.sol/CounselNFT"],
  ["IdentityRegistry", "IdentityRegistryUpgradeable.sol/IdentityRegistryUpgradeable"],
  ["ReputationRegistry", "ReputationRegistryUpgradeable.sol/ReputationRegistryUpgradeable"],
  ["Flywheel", "Flywheel.sol/Flywheel"],
  ["BuybackSwapper", "IBuybackSwapper.sol/IBuybackSwapper"],
  ["UniswapV4PoolSwapper", "UniswapV4PoolSwapper.sol/UniswapV4PoolSwapper"],
  ["MarketplaceAdapter", "IMarketplaceAdapter.sol/IMarketplaceAdapter"],
  ["SeaportAdapter", "SeaportAdapter.sol/SeaportAdapter"],
  ["MockMarketplace", "MockMarketplace.sol/MockMarketplace"],
  ["RewardDistributor", "RewardDistributor.sol/RewardDistributor"],
  ["RevenueRouter", "RevenueRouter.sol/RevenueRouter"],
  ["Incorporations", "Incorporations.sol/Incorporations"],
  ["ProjectFactory", "ProjectFactory.sol/ProjectFactory"],
  ["ContributorDistributor", "ContributorDistributor.sol/ContributorDistributor"],
  ["LaunchGuardHook", "LaunchGuardHook.sol/LaunchGuardHook"],
  ["LaunchToken", "LaunchToken.sol/LaunchToken"],
  ["OracleConsumerExample", "OracleConsumerExample.sol/OracleConsumerExample"],
  ["Create2Deployer", "Create2Deployer.sol/Create2Deployer"],
];

// address-book keys (deployments/<chainId>.json) in a stable order
const ADDRESS_KEYS = [
  "comdToken", // external (Pons); MockComd on test chains
  "counselNFT", // ERC1967 proxy (UUPS): the address holders and apps use
  "counselNFTImpl", // current implementation behind the proxy (informational)
  "identityRegistry",
  "reputationRegistry",
  "rewardDistributor",
  "revenueRouter",
  "flywheel",
  "swapper",
  "incorporations",
  "projectFactory",
  "contributorDistributor",
  "launchGuardHook",
  "create2Deployer",
  "mockMarketplace",
  "seaportAdapter",
  "poolManager",
  "weth",
  "permit2",
  "admin",
  "treasury",
  "keeper",
  "settler",
  "registrar",
];

// external defaults used when a chain has no deployment file yet (COMD_TOKEN comes from the Pons launch)
const EXTERNAL_DEFAULTS = {
  4663: {
    poolManager: "0x8366a39CC670B4001A1121B8F6A443A643e40951",
    weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
  },
  46630: {
    weth: "0x7943e237c7F95DA44E0301572D358911207852Fa",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
  },
};

const ZERO = "0x0000000000000000000000000000000000000000";
const banner = "// GENERATED by scripts/gen-abi.mjs — do not edit by hand.\n";

if (!existsSync(outDir)) {
  console.error(`contracts/out not found at ${outDir} — run \`forge build\` in contracts/ first`);
  process.exit(1);
}

rmSync(abisDir, { recursive: true, force: true });
mkdirSync(abisDir, { recursive: true });
const lower = (s) => s[0].toLowerCase() + s.slice(1);
const index = [banner];
for (const [name, rel] of ARTIFACTS) {
  const file = join(outDir, `${rel}.json`);
  if (!existsSync(file)) {
    console.error(`missing artifact ${file} — run \`forge build\` in contracts/`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(file, "utf8"));
  writeFileSync(
    join(abisDir, `${name}.ts`),
    `${banner}export const ${lower(name)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  index.push(`export { ${lower(name)}Abi } from "./${name}.js";`);
}
writeFileSync(join(abisDir, "index.ts"), index.join("\n") + "\n");

// ---- addresses
const chains = new Map([
  [4663, {}],
  [46630, {}],
]);
if (existsSync(deploymentsDir)) {
  for (const f of readdirSync(deploymentsDir)) {
    const m = /^(\d+)\.json$/.exec(f);
    if (!m) continue;
    chains.set(Number(m[1]), JSON.parse(readFileSync(join(deploymentsDir, f), "utf8")));
  }
}
const lines = [banner];
lines.push(`export type Address = \`0x\${string}\`;`);
lines.push(`export const ZERO_ADDRESS = "${ZERO}" as const;`);
lines.push(`export type ContractName = ${ADDRESS_KEYS.map((k) => JSON.stringify(k)).join(" | ")};`);
lines.push(`export type AddressBook = Record<ContractName, Address> & { chainId: number; deployed: boolean; deployedAtBlock: number };`);
lines.push("");
lines.push("/** Per-chain address book. Missing contracts are the zero address (deployed: false). */");
lines.push("export const addresses: Record<number, AddressBook> = {");
for (const [chainId, dep] of [...chains.entries()].sort((a, b) => a[0] - b[0])) {
  const ext = EXTERNAL_DEFAULTS[chainId] ?? {};
  const deployed = typeof dep.comdToken === "string" && dep.comdToken !== ZERO;
  lines.push(`  ${chainId}: {`);
  lines.push(`    chainId: ${chainId},`);
  lines.push(`    deployed: ${deployed},`);
  lines.push(`    deployedAtBlock: ${Number(dep.deployedAtBlock ?? 0)},`);
  for (const k of ADDRESS_KEYS) {
    const v = dep[k] ?? ext[k] ?? ZERO;
    lines.push(`    ${k}: "${v}",`);
  }
  lines.push("  },");
}
lines.push("};");
lines.push("");
lines.push("export function getAddresses(chainId: number): AddressBook {");
lines.push("  const book = addresses[chainId];");
lines.push("  if (!book) throw new Error(`no address book for chain ${chainId}`);");
lines.push("  return book;");
lines.push("}");
writeFileSync(join(pkg, "src", "addresses.ts"), lines.join("\n") + "\n");
console.log(`wrote ${ARTIFACTS.length} ABIs and addresses for chains ${[...chains.keys()].join(", ")}`);
