// GENERATED by scripts/gen-abi.mjs — do not edit by hand.

export type Address = `0x${string}`;
export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000" as const;
export type ContractName = "comdToken" | "counselNFT" | "counselNFTImpl" | "identityRegistry" | "reputationRegistry" | "rewardDistributor" | "revenueRouter" | "flywheel" | "swapper" | "incorporations" | "projectFactory" | "contributorDistributor" | "launchGuardHook" | "create2Deployer" | "mockMarketplace" | "seaportAdapter" | "poolManager" | "weth" | "permit2" | "admin" | "treasury" | "keeper" | "settler" | "registrar";
export type AddressBook = Record<ContractName, Address> & { chainId: number; deployed: boolean; deployedAtBlock: number };

/** Per-chain address book. Missing contracts are the zero address (deployed: false). */
export const addresses: Record<number, AddressBook> = {
  4663: {
    chainId: 4663,
    deployed: true,
    deployedAtBlock: 81937940,
    comdToken: "0xbFdAc6235dBE77C0CD6EDB01c810c7da858c6c41",
    counselNFT: "0x7d6B060186faB000ad9c54D56FcE447CC22942b7",
    counselNFTImpl: "0x1e2d5495D1398fa22C598677a39054222b1DBfCa",
    identityRegistry: "0x6397A4Ae3738829F2CAF6d0ec08e0db11b579adC",
    reputationRegistry: "0x3F0B04831329625158CfFf56b3341244Dc01c8A4",
    rewardDistributor: "0x2CfbD00723D54E25AF30A06Ad3781B82591b8e64",
    revenueRouter: "0x790d4B37A6a8A3183FBF936D51d23e0d97F349F9",
    flywheel: "0x3674ED844e813E443034ef28B222b58D4901a7Ea",
    swapper: "0x2b6137C6b5609e63E09f00014C48a18196A27421",
    incorporations: "0x44ac164482e105F0d0FD68e5B284D16B5D6999b4",
    projectFactory: "0x17948099ba68413B187206D0BE82F4a35FCeb9b2",
    contributorDistributor: "0xb624A2cadEcb22F9E4AEDECE80921dEb40D8b21c",
    launchGuardHook: "0x5Ff4C8e926C791B7933588b261A9F453D0a62000",
    create2Deployer: "0x506E5E71D46E2EcA38f2Ad70819f8DAD587e94E0",
    mockMarketplace: "0x0000000000000000000000000000000000000000",
    seaportAdapter: "0x0000000000000000000000000000000000000000",
    poolManager: "0x8366a39CC670B4001A1121B8F6A443A643e40951",
    weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    admin: "0xe5375641670C965c264C234839cEbAc9f4e1d2FD",
    treasury: "0xe5375641670C965c264C234839cEbAc9f4e1d2FD",
    keeper: "0x163Bdf367c6B20BC561439bdc0523D49cae6be19",
    settler: "0x4ddFf58eEEC4D838fb9e7069fF48faFCD7a898e0",
    registrar: "0x620962425FF8539ecD9F1D02D71B336d61802D03",
  },
  46630: {
    chainId: 46630,
    deployed: false,
    deployedAtBlock: 0,
    comdToken: "0x0000000000000000000000000000000000000000",
    counselNFT: "0x0000000000000000000000000000000000000000",
    counselNFTImpl: "0x0000000000000000000000000000000000000000",
    identityRegistry: "0x0000000000000000000000000000000000000000",
    reputationRegistry: "0x0000000000000000000000000000000000000000",
    rewardDistributor: "0x0000000000000000000000000000000000000000",
    revenueRouter: "0x0000000000000000000000000000000000000000",
    flywheel: "0x0000000000000000000000000000000000000000",
    swapper: "0x0000000000000000000000000000000000000000",
    incorporations: "0x0000000000000000000000000000000000000000",
    projectFactory: "0x0000000000000000000000000000000000000000",
    contributorDistributor: "0x0000000000000000000000000000000000000000",
    launchGuardHook: "0x0000000000000000000000000000000000000000",
    create2Deployer: "0x0000000000000000000000000000000000000000",
    mockMarketplace: "0x0000000000000000000000000000000000000000",
    seaportAdapter: "0x0000000000000000000000000000000000000000",
    poolManager: "0x0000000000000000000000000000000000000000",
    weth: "0x7943e237c7F95DA44E0301572D358911207852Fa",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    admin: "0x0000000000000000000000000000000000000000",
    treasury: "0x0000000000000000000000000000000000000000",
    keeper: "0x0000000000000000000000000000000000000000",
    settler: "0x0000000000000000000000000000000000000000",
    registrar: "0x0000000000000000000000000000000000000000",
  },
};

export function getAddresses(chainId: number): AddressBook {
  const book = addresses[chainId];
  if (!book) throw new Error(`no address book for chain ${chainId}`);
  return book;
}
