/**
 * The Registrar's standard launch project: a `launch.json` (schema company.launch.v1) plus `script/Launch.s.sol`
 * that calls ProjectFactory.launch(LaunchParams) with the paid economics.
 *
 * Used for `custom_token` launches (ProjectFactory deploys the LaunchToken itself, so the swarm's code is not what
 * gets deployed) and for any launch whose attested tree has no launch.json. Static terms (kind, name, symbol,
 * paired currency, fee tier, opening market cap, pool share, remainder wallet) are written into the script; the
 * per-deployment values come from the Registrar's env:
 *
 *   DEPLOYER_PRIVATE_KEY, PROJECT_FACTORY, CHAIN_ID         (set by @company/services deployLaunch)
 *   LAUNCH_ID          expected ProjectFactory launchId (launchCount() + 1); the script refuses if it moved,
 *                      because CONTRIBUTOR_ROOT's leaves are (launchId, account, amount)
 *   CONTRIBUTOR_ROOT   equal_connected Merkle root of the swarm's 10%
 *   LAUNCH_SALT        CREATE2 salt (keccak256 of the launch record id)
 *   LP_OWNER           policy owners.lpPosition (0 = factory default)
 *
 * No forge-std: the script declares the three cheatcodes it uses, so it compiles offline in a bare sandbox.
 */
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { getAddress, zeroAddress, type Address } from "viem";
import type { LaunchKind } from "@company/protocol";

const KIND_ID: Record<LaunchKind, number> = { custom_token: 0, evm_project: 1, univ4_hook: 2, evm_contracts: 3 };

export interface TemplateInput {
  kind: LaunchKind;
  chainId: number;
  token: { name: string; symbol: string };
  economics: { poolBps: number; initialMarketCapWei: string; remainderTo: string };
  pairWith: Address;
  feeTier: number;
  /** absolute solc path for foundry.toml (`solc = …`); null → `solc_version = "0.8.26"` */
  solc: string | null;
}

const safe = (s: string, re: RegExp, max: number) => s.replace(re, "").slice(0, max);

export function launchScript(t: TemplateInput): string {
  const name = safe(t.token.name, /[^A-Za-z0-9 .-]/g, 64) || "Launch";
  const symbol = safe(t.token.symbol, /[^A-Za-z0-9]/g, 11).toUpperCase() || "LAUNCH";
  const remainder = getAddress(t.economics.remainderTo);
  const paired = getAddress(t.pairWith);
  if (!/^[0-9]+$/.test(t.economics.initialMarketCapWei)) throw new Error("initialMarketCapWei must be a decimal string");
  return `// SPDX-License-Identifier: MIT
// Generated by the Registrar (Company.md) for a ${t.kind} launch on chain ${t.chainId}. UNAUDITED.
pragma solidity ^0.8.26;

interface Vm {
    function envUint(string calldata name) external view returns (uint256);
    function envAddress(string calldata name) external view returns (address);
    function envBytes32(string calldata name) external view returns (bytes32);
    function startBroadcast(uint256 privateKey) external;
    function stopBroadcast() external;
}

interface IProjectFactory {
    struct LaunchParams {
        uint8 kind;
        string name;
        string symbol;
        uint256 totalSupply;
        address paired;
        uint24 fee;
        address hook;
        uint256 initialMarketCap;
        uint16 poolBps;
        address remainderTo;
        bytes32 contributorRoot;
        bytes32 salt;
        address lpOwner;
    }

    function launch(LaunchParams calldata p) external returns (uint256 launchId, address token);
    function launchCount() external view returns (uint256);
}

contract Launch {
    Vm internal constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    function run() external returns (address token, address factory) {
        require(block.chainid == vm.envUint("CHAIN_ID"), "wrong chain");
        uint256 pk = vm.envUint("DEPLOYER_PRIVATE_KEY");
        factory = vm.envAddress("PROJECT_FACTORY");
        IProjectFactory f = IProjectFactory(factory);
        uint256 expected = vm.envUint("LAUNCH_ID");
        require(f.launchCount() + 1 == expected, "launchId moved: rebuild the contributor root");
        IProjectFactory.LaunchParams memory p = IProjectFactory.LaunchParams({
            kind: ${KIND_ID[t.kind]},
            name: "${name}",
            symbol: "${symbol}",
            totalSupply: 0,
            paired: ${paired},
            fee: ${Number(t.feeTier)},
            hook: address(0),
            initialMarketCap: ${t.economics.initialMarketCapWei},
            poolBps: ${Number(t.economics.poolBps)},
            remainderTo: ${remainder},
            contributorRoot: vm.envBytes32("CONTRIBUTOR_ROOT"),
            salt: vm.envBytes32("LAUNCH_SALT"),
            lpOwner: vm.envAddress("LP_OWNER")
        });
        vm.startBroadcast(pk);
        (uint256 launchId, address t) = f.launch(p);
        vm.stopBroadcast();
        require(launchId == expected, "unexpected launchId");
        token = t;
    }
}
`;
}

export function launchManifest(t: TemplateInput) {
  return {
    schema: "company.launch.v1",
    kind: t.kind,
    chainId: t.chainId,
    script: "script/Launch.s.sol:Launch",
    token: { name: safe(t.token.name, /[^A-Za-z0-9 .-]/g, 64) || "Launch", symbol: safe(t.token.symbol, /[^A-Za-z0-9]/g, 11).toUpperCase() || "LAUNCH" },
    pool: { pairWith: t.pairWith.toLowerCase() === zeroAddress ? "eth" : t.pairWith.toLowerCase(), feeTier: t.feeTier },
    economics: { poolBps: t.economics.poolBps, initialMarketCapWei: t.economics.initialMarketCapWei, remainderTo: getAddress(t.economics.remainderTo) },
  };
}

/** Write the template project to a fresh temp dir and return it. */
export async function writeLaunchTemplate(t: TemplateInput): Promise<string> {
  const dir = await mkdtemp(path.join(tmpdir(), "company-launch-"));
  await mkdir(path.join(dir, "script"), { recursive: true });
  const toml = [
    "[profile.default]",
    'src = "script"',
    'script = "script"',
    'out = "out"',
    "libs = []",
    'evm_version = "cancun"',
    "optimizer = true",
    t.solc ? `solc = ${JSON.stringify(t.solc)}` : 'solc_version = "0.8.26"',
    "",
  ].join("\n");
  await writeFile(path.join(dir, "foundry.toml"), toml);
  await writeFile(path.join(dir, "launch.json"), JSON.stringify(launchManifest(t), null, 2));
  await writeFile(path.join(dir, "script", "Launch.s.sol"), launchScript(t));
  return dir;
}
